apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: boiling-wasp-go 
  janus-idp.io/tekton: boiling-wasp-go
  backstage.io/kubernetes-id: boiling-wasp-go
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: boiling-wasp-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  