apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: boiling-wasp-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: boiling-wasp-go 
  name: boiling-wasp-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: boiling-wasp-go 
